# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin:
    resource: '@SyliusAdminBundle/Resources/config/routing.yml'
    prefix: /admin

sylius_api:
    resource: '@SyliusAdminApiBundle/Resources/config/routing.yml'
    prefix: /api

our_routing:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /

sylius_shop:
    resource: '@SyliusShopBundle/Resources/config/routing.yml'
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

sylius_shop_payum:
    resource: '@SyliusShopBundle/Resources/config/routing/payum.yml'

sylius_shop_default_locale:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.locale_switch:switchAction

_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.yaml'

#info_contact:
#   resource: |
#       alias: app.infocontact
#       section: admin
#   type: sylius.resource
#   prefix: /administration
#   defaults:
#        _sylius:
#            permission: false
