# config/resources.yaml
sylius_resource:
    resources:
        app.infocontact:
            driver: doctrine/orm # You can use also different driver here
            classes:
                model: AppBundle\Entity\infocontact
